CREATE SCHEMA pam_0_1_7;

CREATE TABLE pam_0_1_7.shapes
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objectID integer REFERENCES pam.objects (id),
	fieldID integer,
	shape geometry,
	acres float,
	metadata jsonb
)
WITH (
    OIDS = FALSE
);