//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.timmons.cognitive.API.SQL.DynamicObject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.timmons.cognitive.API.SQL.DynamicObject.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE $_$_SCHEMA_$_$.objects
        ///	SET deleted = true
        ///WHERE
        ///	id=@id.
        /// </summary>
        internal static string DynamicObject_DeleteSingle {
            get {
                return ResourceManager.GetString("DynamicObject_DeleteSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO $_$_SCHEMA_$_$.objects_$_$_KEY_$_$
        ///	( name
        ///	, &quot;createdBy&quot;
        ///	, &quot;lastModifiedBy&quot;
        ///	, fields
        ///	)
        ///VALUES
        ///    (@name
        ///    , @createdByID
        ///    , @createdByID
        ///    , CAST(@fields as jsonb)
        ///    )
        ///RETURNING id.
        /// </summary>
        internal static string DynamicObject_InsertSingle {
            get {
                return ResourceManager.GetString("DynamicObject_InsertSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	o.id, 
        ///	o.name,
        ///	o.deleted, 
        ///	o.fields,
        ///	CAST(EXTRACT(EPOCH FROM o.created) AS bigint ) as created,
        ///	CAST(EXTRACT(EPOCH FROM o.modified) AS bigint ) as modified,
        ///	o.&quot;createdBy&quot; as id,
        ///	o.&quot;lastModifiedBy&quot; as id
        ///FROM $_$_SCHEMA_$_$.objects_$_$_KEY_$_$ as o
        ///WHERE o.deleted = false.
        /// </summary>
        internal static string DynamicObject_ReadAllOfType {
            get {
                return ResourceManager.GetString("DynamicObject_ReadAllOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    o.id as id, 
        ///    o.name as name,
        ///    o.deleted as deleted, 
        ///    o.fields as fields,
        ///    CAST(EXTRACT(EPOCH FROM o.created) AS bigint ) as created,
        ///    CAST(EXTRACT(EPOCH FROM o.modified) AS bigint ) as modified,
        ///    o.&quot;createdBy&quot; as id, 
        ///    o.&quot;lastModifiedBy&quot; as id
        ///FROM $_$_SCHEMA_$_$.objects_$_$_KEY_$_$ as o
        ///WHERE o.id=@id
        ///    AND o.deleted = false.
        /// </summary>
        internal static string DynamicObject_ReadSingle {
            get {
                return ResourceManager.GetString("DynamicObject_ReadSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE $_$_SCHEMA_$_$.objects_$_$_KEY_$_$
        ///	SET name=@name
        ///	, &quot;lastModifiedBy&quot;=@lastModifiedById
        ///	, fields = CAST(@fields as jsonb)
        ///	, modified = NOW()
        ///WHERE id = @id
        ///RETURNING id.
        /// </summary>
        internal static string DynamicObject_UpdateSingle {
            get {
                return ResourceManager.GetString("DynamicObject_UpdateSingle", resourceCulture);
            }
        }
    }
}
