version: 0.2

phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore API.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./api API.csproj
      - echo "Listing files in database deployment."
      - find ./Database\ Deployment/
      - dotnet publish -c release -o ./api/database "./Database Deployment/DatabaseDeployment.csproj"
      - cp buildspec-bundle.yml ./api/buildspec.yml
      - mkdir -p ./api/Docker
      - cp ./Docker/* ./api/Docker/
      - find ./api
artifacts:
    base-directory: api
    files:
        - "**/*"