CREATE TABLE IF NOT EXISTS pam_3_0_0.event_type
(
    "type" uuid NOT NULL,
    "name" character varying(250) NOT NULL,
    "description" text,

    CONSTRAINT pk_event_type PRIMARY KEY ("type")
);

CREATE TABLE IF NOT EXISTS pam_3_0_0.events
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "type" uuid NOT NULL,
    "date" timestamp with time zone DEFAULT now(),
    who uuid NOT NULL,
    data jsonb,

    CONSTRAINT pk_event_id PRIMARY KEY (id),
    CONSTRAINT fk_event_type FOREIGN KEY ("type")
        REFERENCES pam_3_0_0.event_type("type") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
);