CREATE TABLE pam_3_0_0.object_layout_section
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    layoutid integer NOT NULL,
    modelid integer NOT NULL,
    enabled boolean,
    "order" integer,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    editable boolean,
    layout jsonb
)
WITH (
    OIDS = FALSE
);