CREATE TABLE pam_2_0_0.objects_template
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone DEFAULT now(),
    modified timestamp with time zone DEFAULT now(),
    "createdBy" uuid NOT NULL,
    "lastModifiedBy" uuid NOT NULL,
    deleted boolean DEFAULT false,
    fields jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT objects_template_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);