AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Multi level base path mapping

Parameters:
  DomainName:
    Type: String
    Description: Domian name for api
  SecurityGroup1:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for API (To access rds?)
  SecurityGroup2:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for API (To access rds?)
  Subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for api (To access rds?)
  Subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for api (To access rds?)
  SSMPath:
    Type: String
    Description: Base path in SSM the api will read config from
  API_Repository:
    Type: String
    Description: URI to api image

Resources:
  APIMapping: # Creates the mapping for Reporting V1
    Type: AWS::ApiGatewayV2::ApiMapping
    DependsOn: API
    Properties: 
      ApiId: !Ref API
      ApiMappingKey: "api"
      DomainName: !Ref DomainName
      Stage: !Ref API.Stage

  API: # endpoint
    Type: AWS::Serverless::Api
    Properties:
      Description: !Sub "${DomainName} - API"
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
        x-amazon-apigateway-importexport-version: "1.0"


  APIFn:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageUri: !Ref API_Repository
      Events:
        API:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref API
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          SSMPath: !Ref SSMPath
      VpcConfig:
        SecurityGroupIds:
            - !Ref SecurityGroup1
            - !Ref SecurityGroup2
        SubnetIds:
            - !Ref Subnet1
            - !Ref Subnet2
    Metadata:
      DockerTag: dotnet5.0-v1
      DockerContext: ../Backend
      Dockerfile: Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: run