CREATE TABLE pam_1_0_0.shapes
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    objectID integer REFERENCES pam_1_0_0.objects (id),
	fieldID integer,
	shape geometry,
	acres float,
	metadata jsonb
)
WITH (
    OIDS = FALSE
);