CREATE TABLE pam_1_0_0.capabilities
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" character varying (50),
    "version" character varying (50),
    "added" TIMESTAMP DEFAULT now()
)
WITH (
    OIDS = FALSE
);


CREATE VIEW pam.capabilities AS
    SELECT *
    FROM pam_1_0_0.capabilities;