CREATE TABLE pam_1_0_0.gridViews
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type integer REFERENCES pam_1_0_0.model (id),
    layout jsonb DEFAULT '{}'
)
WITH (
    OIDS = FALSE
);

CREATE TABLE pam_1_0_0.detailViews
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type integer REFERENCES pam_1_0_0.model (id),
    layout jsonb DEFAULT '{}'
)
WITH (
    OIDS = FALSE
);

CREATE TABLE pam_1_0_0.choiceRepo
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type integer REFERENCES pam_1_0_0.model (id),
    choices jsonb DEFAULT '{}'
)
WITH (
    OIDS = FALSE
);

CREATE OR REPLACE VIEW pam.gridViews AS
 SELECT *
   FROM pam_1_0_0.gridViews;

CREATE OR REPLACE VIEW pam.detailViews AS
 SELECT *
   FROM pam_1_0_0.detailViews;

CREATE OR REPLACE VIEW pam.choiceRepo AS
 SELECT *
   FROM pam_1_0_0.choiceRepo;