CREATE TABLE pam_1_0_0.appConfig
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created timestamp with time zone DEFAULT NOW(),
    config jsonb DEFAULT '{}'
)
WITH (
    OIDS = FALSE
);


CREATE OR REPLACE VIEW pam.appConfig as 
	SELECT * FROM pam_1_0_0.appConfig;