CREATE SCHEMA pam;

CREATE TABLE pam.model
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key character varying(50) NOT NULL,
    singular_name character varying(50) NOT NULL,
    plural_name character varying(50) NOT NULL,
    display boolean NOT NULL,
    display_order integer NOT NULL UNIQUE,
    model jsonb DEFAULT '{}'
)
WITH (
    OIDS = FALSE
);


CREATE TABLE pam.objects
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    type integer NOT NULL,
	created timestamp with time zone DEFAULT NOW(),
	modified timestamp with time zone DEFAULT NOW(),
    "createdBy" uuid NOT NULL,
    "lastModifiedBy" uuid NOT NULL,
    deleted boolean DEFAULT FALSE,
    fields jsonb DEFAULT '{}'
)
WITH (
    OIDS = FALSE
);

CREATE TABLE pam.choices
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	objectType integer NOT NULL,
    type integer NOT NULL,
	value character varying(50) NOT NULL
)
WITH (
    OIDS = FALSE
);

CREATE TABLE pam.layouts
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	objectType integer NOT NULL,
    type integer NOT NULL,
	layout jsonb DEFAULT '{}'
)
WITH (
    OIDS = FALSE
);