CREATE TABLE pam_0_1_10.scoreLayers
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(250) NOT NULL,
    settings jsonb,
    normalization FLOAT
)
WITH (
    OIDS = FALSE
);


CREATE TABLE pam_0_1_10.estimatedScoreGrid
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "row" INTEGER,
    "column" INTEGER,
    layer INT REFERENCES pam_0_1_10.scoreLayers (id),
    "score" FLOAT,
    "min" FLOAT,
    "max" FLOAT,
    "avg" FLOAT,
	shape geometry
)
WITH (
    OIDS = FALSE
);