CREATE TABLE pam_0_1_10.shapeScoreEstimatedParts
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shape INT REFERENCES pam_0_1_7.shapes (id),
    fullyWithin BOOLEAN,
    gridID INT REFERENCES pam_0_1_10.estimatedScoreGrid
    
)
WITH (
    OIDS = FALSE
);