
CREATE TABLE pam_0_1_10.bands
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    layer integer,
    value double precision,
    range numrange,
    label character varying(50),
    CONSTRAINT bands_pkey PRIMARY KEY (id),
    CONSTRAINT bands_layer_fkey FOREIGN KEY (layer)
        REFERENCES pam_0_1_10.scorelayers (id) MATCH SIMPLE
)