CREATE SCHEMA IF NOT EXISTS stitch;

CREATE TABLE IF NOT EXISTS stitch.appconfig
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created timestamp with time zone DEFAULT now(),
    appname character varying(50) COLLATE pg_catalog."default",
    config jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT appconfig_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
);